import type { FooterState } from "../types";

export type ExportPayload = { fileName: string; mimeType: "text/plain;charset=utf-8"; content: string };

export function buildExportPayload(state: FooterState, fileName = "footers") : ExportPayload {
  return { fileName: `${fileName || "footers"}.jsx`, mimeType: "text/plain;charset=utf-8", content: buildReactCode(state) };
}

export function buildReactCode(state: FooterState) {
  return [
    "import * as React from \"react\";",
    "",
    "const state = " + JSON.stringify(state, null, 2) + ";",
    "",
    "export default function FooterComponent() {",
    "  const columns = Array.from({ length: state.columnCount }, (_, index) => `Column ${index + 1}`);",
    "  const links = Array.from({ length: state.linkCount }, (_, index) => `Link ${index + 1}`);",
    "  const compact = state.previewState === \"collapsed\" || state.previewState === \"mobile\";",
    "  const style = {",
    "    width: state.width,",
    "    minHeight: state.height,",
    "    padding: state.padding,",
    "    margin: state.margin,",
    "    gap: state.gap,",
    "    borderRadius: state.radius,",
    "    border: `${state.borderWidth}px solid ${state.border}`,",
    "    boxShadow: `0 ${Math.round(state.shadow / 3)}px ${state.shadow}px rgba(0,0,0,.28)`,",
    "    background: state.background,",
    "    color: state.foreground,",
    "    fontFamily: state.fontFamily,",
    "    transition: state.motion ? \"all 180ms ease\" : undefined,",
    "  };",
    "",
    "  return (",
    "    <footer id={state.id} aria-label={state.landmarkLabel} tabIndex={state.tabIndex} style={style}>",
    "      <div style={{ display: \"grid\", gap: state.gap }}>",
    "        <section aria-labelledby={`${state.id}-brand`} style={{ display: \"grid\", gap: Math.max(8, state.gap / 2) }}>",
    "          <h2 id={`${state.id}-brand`} style={{ fontSize: state.titleSize, fontWeight: state.fontWeight }}>{state.title}</h2>",
    "          <p style={{ color: state.muted, fontSize: state.bodySize, maxWidth: 620 }}>{state.description}</p>",
    "          {state.showNewsletter && (",
    "            <form onSubmit={(event) => event.preventDefault()} style={{ display: \"flex\", flexWrap: \"wrap\", gap: Math.max(8, state.gap / 2) }}>",
    "              <label htmlFor={`${state.id}-email`} style={{ position: \"absolute\", width: 1, height: 1, padding: 0, margin: -1, overflow: \"hidden\", clip: \"rect(0,0,0,0)\", whiteSpace: \"nowrap\", border: 0 }}>Email address</label>",
    "              <input id={`${state.id}-email`} type=\"email\" placeholder=\"you@example.com\" style={{ border: `1px solid ${state.border}`, borderRadius: 999, padding: \"8px 16px\", background: \"transparent\", color: state.foreground }} />",
    "              <button type=\"submit\" style={{ border: 0, borderRadius: 999, padding: \"8px 16px\", background: state.accent, color: state.background, fontWeight: 700 }}>Subscribe</button>",
    "            </form>",
    "          )}",
    "        </section>",
    "        <nav aria-label={`${state.landmarkLabel} links`} style={{ display: \"grid\", gap: state.gap, gridTemplateColumns: compact ? \"1fr\" : `repeat(${state.columnCount}, minmax(0, 1fr))` }}>",
    "          {columns.map((column, columnIndex) => (",
    "            <section key={column} aria-labelledby={`${state.id}-column-${columnIndex}`} style={{ display: \"grid\", alignContent: \"start\", gap: Math.max(6, state.gap / 2) }}>",
    "              <h3 id={`${state.id}-column-${columnIndex}`} style={{ color: state.accent, textTransform: \"uppercase\", letterSpacing: \".16em\", fontSize: 12 }}>{column}</h3>",
    "              {links.filter((_, index) => index % columns.length === columnIndex).map((link, linkIndex) => (",
    "                <a key={link} href=\"#\" aria-current={state.previewState === \"active\" && columnIndex === 0 && linkIndex === 0 ? \"page\" : undefined} style={{ color: state.previewState === \"hover\" && linkIndex === 0 ? state.foreground : state.muted, textDecoration: \"none\" }}>{link}</a>",
    "              ))}",
    "            </section>",
    "          ))}",
    "        </nav>",
    "        <div style={{ display: \"flex\", flexWrap: \"wrap\", alignItems: \"center\", justifyContent: \"space-between\", borderTop: `1px solid ${state.border}`, paddingTop: 16, gap: state.gap }}>",
    "          {state.showLegal && <small style={{ color: state.muted }}>Copyright 2026 {state.title}. Privacy, Terms, Security.</small>}",
    "          {state.showSocial && <nav aria-label={`${state.landmarkLabel} social links`} style={{ display: \"flex\", gap: Math.max(8, state.gap / 2) }}>{[\"X\", \"In\", \"Git\"].map((item) => <a key={item} href=\"#\" style={{ border: `1px solid ${state.border}`, borderRadius: 999, padding: \"8px 12px\", color: state.foreground, fontWeight: 700, textDecoration: \"none\" }}>{item}</a>)}</nav>}",
    "        </div>",
    "      </div>",
    "    </footer>",
    "  );",
    "}",
    "",
  ].join("\n");
}
